In [1]:
!pip install pandas
!pip install pyreadr
!pip install sdmetrics

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: pandas in /opt/conda/lib/python3.8/site-packages (1.2.5)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.8/site-packages (from pandas) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.8/site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.16.5 in /opt/conda/lib/python3.8/site-packages (from pandas) (1.21.4)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting pyreadr
  Downloading pyreadr-0.4.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (364 kB)
     |████████████████████████████████| 364 kB 5.6 MB/s eta 0:00:01
Requirement already satisfied: pandas>=1.2.0 in /opt/conda/lib/python3.8/site-packages (from pyreadr) (1.2.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.8/site-packages (from pandas>=1.2.0->pyreadr) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.8/site-packages (from pandas>=1.2.0->pyreadr) (2021.3)
Requirement already satisfied: numpy>=1.16.5 in /opt/conda/lib/python3.8/site-packages (from pandas>=1.2.0->pyreadr) (1.21.4)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas>=1.2.0->pyreadr) (1.16.0)
Installing collected packages: pyreadr
Successfully installed pyreadr-0.4.7
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting sdmetrics
  Downloading sdmetrics-0.9.0-py2.py3-none-any.whl (140 kB)
     |████████████████████████████████| 140 kB 6.0 MB/s eta 0:00:01
Requirement already satisfied: scipy<2,>=1.5.4 in /opt/conda/lib/python3.8/site-packages (from sdmetrics) (1.6.3)
Collecting scikit-learn<2,>=0.24
  Downloading scikit_learn-1.2.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.7 MB)
     |████████████████████████████████| 9.7 MB 42.1 MB/s eta 0:00:01
Collecting plotly<6,>=5.10.0
  Downloading plotly-5.13.0-py2.py3-none-any.whl (15.2 MB)
     |████████████████████████████████| 15.2 MB 109.5 MB/s eta 0:00:01
Collecting copulas<0.9,>=0.8.0
  Downloading copulas-0.8.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 83.7 MB/s  eta 0:00:01
Requirement already satisfied: pandas<2,>=1.1.3 in /opt/conda/lib/python3.8/site-packages (from sdmetrics) (1.2.5)
Requirement already satisfied: numpy<2,>=1.20.0 in /opt/conda/lib/python3.8/site-packages (from sdmetrics) (1.21.4)
Requirement already satisfied: tqdm<5,>=4.15 in /opt/conda/lib/python3.8/site-packages (from sdmetrics) (4.62.3)
Requirement already satisfied: matplotlib<4,>=3.4.0 in /opt/conda/lib/python3.8/site-packages (from copulas<0.9,>=0.8.0->sdmetrics) (3.4.3)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.8/site-packages (from matplotlib<4,>=3.4.0->copulas<0.9,>=0.8.0->sdmetrics) (8.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.8/site-packages (from matplotlib<4,>=3.4.0->copulas<0.9,>=0.8.0->sdmetrics) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/conda/lib/python3.8/site-packages (from matplotlib<4,>=3.4.0->copulas<0.9,>=0.8.0->sdmetrics) (3.0.5)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.8/site-packages (from matplotlib<4,>=3.4.0->copulas<0.9,>=0.8.0->sdmetrics) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.8/site-packages (from matplotlib<4,>=3.4.0->copulas<0.9,>=0.8.0->sdmetrics) (1.3.2)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.8/site-packages (from pandas<2,>=1.1.3->sdmetrics) (2021.3)
Collecting tenacity>=6.2.0
  Downloading tenacity-8.1.0-py3-none-any.whl (23 kB)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib<4,>=3.4.0->copulas<0.9,>=0.8.0->sdmetrics) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.8/site-packages (from scikit-learn<2,>=0.24->sdmetrics) (3.0.0)
Collecting joblib>=1.1.1
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     |████████████████████████████████| 297 kB 1.7 MB/s eta 0:00:01
Installing collected packages: tenacity, joblib, scikit-learn, plotly, copulas, sdmetrics
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.23.1
    Uninstalling scikit-learn-0.23.1:
      Successfully uninstalled scikit-learn-0.23.1
Successfully installed copulas-0.8.0 joblib-1.2.0 plotly-5.13.0 scikit-learn-1.2.0 sdmetrics-0.9.0 tenacity-8.1.0

In [6]:
import pandas as pd
import pyreadr
import os

from sdmetrics.single_table import NewRowSynthesis

In [7]:
# mount to the working directory
wd = "/dss/dsshome1/0C/ru27req2/MA_Experiment_Data/Master-Thesis-DifferentialPrivacy"
os.chdir(wd)

In [28]:
# read in the original dataset as dictionary
ods_dict = pyreadr.read_r("bindori_dataset_preprocessed_factor.rda")

In [52]:
# # done! let's see what we got
# # print(ods_dict.keys()) # odict_keys(['bindori_dataset_threshold_chr'])
# ods_dataset = ods_dict["bindori_dataset_threshold_chr"]
# # ods_dataset

# # preprocess the dataset to keep only 54 variables
# ods_dataset.drop(["B13_1", "B13_2", "B13_3", "B13_4",
#                   "B13_5", "B13_6", "B13_7", "B14_1", 
#                   "B14_2", "B14_3", "B14_4", "B14_5",
#                   "D6_1", "D6_2", "D6_3", "F3_de",
#                   "B1b_x1", "B1b_x2", "B1b_x3", "B1b_x4", 
#                   "B1b_x5", "B1b_x6", "B1b_x7", "B1b_x8", 
#                   "B1b_x9", "B1b_x10", "B1b_x11","B1b_x12", 
#                   "B1b_x13", "D10", "C0_1", "C0_2", 
#                   "C0_3", "C0_4", "C0_5", "C0_6"], inplace=True, axis=1)
ods_dataset.iloc[:, 1:54]

,B1_1,B1_2,B1_3,B1_4,B1_5,B1_6,B1_7,B1_8,B1_9,B1_10,...,E3,E4,E7,F1,F2_1,F2_2,B2,B4,E5,E6
0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,1.0,3.0,5.0,1.0,2.0,2.0,2.0,1.0,3.0,2.0
1,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,-99.0,-99.0,-99.0,-99.0,-99.0,-99.0,2.0,1.0,1.0,1.0
2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,1.0,4.0,3.0,1.0,2.0,2.0,2.0,1.0,3.0,2.0
3,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,...,-99.0,5.0,3.0,1.0,2.0,2.0,4.0,1.0,3.0,2.0
4,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,-99.0,-99.0,-99.0,-99.0,-99.0,-99.0,2.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260294,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,1.0,7.0,3.0,1.0,2.0,2.0,2.0,1.0,3.0,2.0
260295,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,4.0,4.0,1.0,2.0,2.0,2.0,1.0,3.0,2.0
260296,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,3.0,2.0
260297,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,3.0,1.0,2.0,2.0,2.0,1.0,3.0,2.0
260298,2.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,...,1.0,4.0,4.0,1.0,2.0,2.0,4.0,1.0,3.0,2.0

In [30]:
# encode var B2, B4, E5, E6 as integers
# prepare the category mapping
category_mapping_B2 = {'-1': 1, '-99': 2, '[0, 1)': 3, '[1, 3)': 4}
category_mapping_B4 = {'-99': 1, '[0, 1)': 2, '[1, 5)': 3}
category_mapping_E5 = {'-99': 1, '[0, 1)': 2, '[1, 2)': 3}
category_mapping_E6 = {'-99': 1, '[0, 9)': 2}

ods_dataset['B2'] = ods_dataset['B2'].map(category_mapping_B2)
ods_dataset['B4'] = ods_dataset['B4'].map(category_mapping_B4)
ods_dataset['E5'] = ods_dataset['E5'].map(category_mapping_E5)
ods_dataset['E6'] = ods_dataset['E6'].map(category_mapping_E6)

In [50]:
# change from column 1-54 as float variables
ods_dataset.iloc[:,1:54] = ods_dataset.iloc[:,1:54].astype(float)

### 2-1 read in the `cart` group synthetic datasets
There are in total 3 datasets generated using this method, which are
- cart_sample_sds
- cart_norm_sds
- cart_normrank_sds

In [53]:
# load the cart synthetic datasets
cart_sample_sds = pyreadr.read_r("./SyntheticData/Yue/syn1_cart/cart_sample_syn.rda")["syn"]
cart_norm_sds = pyreadr.read_r("./SyntheticData/Yue/syn1_cart/cart_norm_syn.rda")["syn"]
cart_normrank_sds = pyreadr.read_r("./SyntheticData/Yue/syn1_cart/cart_normrank_syn.rda")["syn"]

# # reverse the encoding based on B2, B4, E5, E6
# # for B2
# cart_sample_sds['B2'].replace(1, "-1", inplace=True)
# cart_sample_sds['B2'].replace(2, "-99", inplace=True)
# cart_sample_sds['B2'].replace(3, "[0, 1)", inplace=True)
# cart_sample_sds['B2'].replace(4, "[1, 3)", inplace=True)
# cart_norm_sds['B2'].replace(1, "-1", inplace=True)
# cart_norm_sds['B2'].replace(2, "-99", inplace=True)
# cart_norm_sds['B2'].replace(3, "[0, 1)", inplace=True)
# cart_norm_sds['B2'].replace(4, "[1, 3)", inplace=True)
# cart_normrank_sds['B2'].replace(1, "-1", inplace=True)
# cart_normrank_sds['B2'].replace(2, "-99", inplace=True)
# cart_normrank_sds['B2'].replace(3, "[0, 1)", inplace=True)
# cart_normrank_sds['B2'].replace(4, "[1, 3)", inplace=True)

# # for B4
# cart_sample_sds['B4'].replace(1, "-99", inplace=True)
# cart_sample_sds['B4'].replace(2, "[0, 1)", inplace=True)
# cart_sample_sds['B4'].replace(3, "[1, 5)", inplace=True)
# cart_norm_sds['B4'].replace(1, "-99", inplace=True)
# cart_norm_sds['B4'].replace(2, "[0, 1)", inplace=True)
# cart_norm_sds['B4'].replace(3, "[1, 5)", inplace=True)
# cart_normrank_sds['B4'].replace(1, "-99", inplace=True)
# cart_normrank_sds['B4'].replace(2, "[0, 1)", inplace=True)
# cart_normrank_sds['B4'].replace(3, "[1, 5)", inplace=True)

# # for E5
# cart_sample_sds['E5'].replace(1, "-99", inplace=True)
# cart_sample_sds['E5'].replace(2, "[0, 1)", inplace=True)
# cart_sample_sds['E5'].replace(3, "[1, 2)", inplace=True)
# cart_norm_sds['E5'].replace(1, "-99", inplace=True)
# cart_norm_sds['E5'].replace(2, "[0, 1)", inplace=True)
# cart_norm_sds['E5'].replace(3, "[1, 2)", inplace=True)
# cart_normrank_sds['E5'].replace(1, "-99", inplace=True)
# cart_normrank_sds['E5'].replace(2, "[0, 1)", inplace=True)
# cart_normrank_sds['E5'].replace(3, "[1, 2)", inplace=True)

# # for E6
# cart_sample_sds['E6'].replace(1, "-99", inplace=True)
# cart_sample_sds['E6'].replace(2, "[0, 9)", inplace=True)
# cart_norm_sds['E6'].replace(1, "-99", inplace=True)
# cart_norm_sds['E6'].replace(2, "[0, 9)", inplace=True)
# cart_normrank_sds['E6'].replace(1, "-99", inplace=True)
# cart_normrank_sds['E6'].replace(2, "[0, 9)", inplace=True)

In [57]:
# change from column 1-54 as float variables
cart_sample_sds.iloc[:,1:54] = cart_sample_sds.iloc[:,1:54].astype(float)
cart_norm_sds.iloc[:,1:54] = cart_norm_sds.iloc[:,1:54].astype(float)
cart_normrank_sds.iloc[:,1:54] = cart_normrank_sds.iloc[:,1:54].astype(float)

In [60]:
cart_norm_sds.head()

,weight,B1_1,B1_2,B1_3,B1_4,B1_5,B1_6,B1_7,B1_8,B1_9,...,E3,E4,E7,F1,F2_1,F2_2,B2,B4,E5,E6
0,7208.333736,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,1.0,3.0,1.0,1.0,2.0,2.0,2.0,1.0,3.0,2.0
1,3739.736757,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,...,2.0,5.0,4.0,1.0,2.0,2.0,4.0,1.0,2.0,2.0
2,14325.886161,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,-99.0,-99.0,-99.0,-99.0,-99.0,-99.0,2.0,1.0,1.0,1.0
3,2183.540969,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,...,2.0,3.0,5.0,1.0,1.0,1.0,4.0,1.0,3.0,2.0
4,6540.557251,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,5.0,2.0,1.0,1.0,2.0,2.0,3.0,3.0,2.0

In [62]:
# create the metadata dictionary
single_table_metadata_dict = {"primary_key": "weight",
                              "fields": {
                                "weight": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B1_1": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B1_2": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B1_3": {
                                    "type": "numerical",
                                    "subtype": "float",
                                }, 
                                "B1_4": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B1_5": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B1_6": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B1_7": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B1_8": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B1_9": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B1_10": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B1_11": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B1_12": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B1_13": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B3": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B5": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B6": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B7": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B8": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B9": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B10": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B11": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B12_1": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B12_2": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B12_3": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B12_4": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B12_5": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B12_6": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "C1_m": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "C2": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "C3": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "C5": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "C6": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "C7": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "C8": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "D1": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "D2": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "D3": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "D4": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "D5": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "D7": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "D8": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "D9": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "E2": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "E3": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "E4": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "E7": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "F1": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "F2_1": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "F2_2": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B2": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "B4": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "E5": {
                                    "type": "numerical",
                                    "subtype": "float",
                                },
                                "E6": {
                                    "type": "numerical",
                                    "subtype": "float",
                                }
                            }}

In [ ]:
# type(cart_sample_sds["weight"][1])

# cart_sample_sds.iloc[:, 2:54]
NewRowSynthesis.compute(
    real_data=ods_dataset,
    synthetic_data=cart_sample_sds,
    metadata=single_table_metadata_dict,
    numerical_match_tolerance=0.01,
    synthetic_sample_size=10_000
)

In [50]:
from sdmetrics import load_demo
from sdmetrics.reports.single_table import QualityReport

real_data, synthetic_data, metadata = load_demo(modality='single_table')

my_report = QualityReport()
my_report.generate(real_data, synthetic_data, metadata)

Creating report: 100%|██████████| 4/4 [00:00<00:00,  7.03it/s]

Overall Quality Score: 81.44%

Properties:
Column Shapes: 81.56%
Column Pair Trends: 81.33%

In [18]:
cart_sample_sds.iloc[:, 0:2]

              weight B1_1
0       15913.937193  -99
1        4857.515863    2
2        6949.864949    2
3        7733.445343    2
4       11608.212078    2
...              ...  ...
260294  29020.142510    2
260295  16201.928092    2
260296   6440.465438    2
260297   3494.649418    2
260298   7080.282151    2

[260299 rows x 2 columns]

In [51]:
metadata

{'fields': {'start_date': {'type': 'datetime', 'format': '%Y-%m-%d'},
  'end_date': {'type': 'datetime', 'format': '%Y-%m-%d'},
  'salary': {'type': 'numerical', 'subtype': 'integer'},
  'duration': {'type': 'numerical', 'subtype': 'integer'},
  'student_id': {'type': 'id', 'subtype': 'integer'},
  'high_perc': {'type': 'numerical', 'subtype': 'float'},
  'high_spec': {'type': 'categorical'},
  'mba_spec': {'type': 'categorical'},
  'second_perc': {'type': 'numerical', 'subtype': 'float'},
  'gender': {'type': 'categorical'},
  'degree_perc': {'type': 'numerical', 'subtype': 'float'},
  'placed': {'type': 'boolean'},
  'experience_years': {'type': 'numerical', 'subtype': 'float'},
  'employability_perc': {'type': 'numerical', 'subtype': 'float'},
  'mba_perc': {'type': 'numerical', 'subtype': 'float'},
  'work_experience': {'type': 'boolean'},
  'degree_type': {'type': 'categorical'}},
 'constraints': [],
 'model_kwargs': {},
 'name': None,
 'primary_key': 'student_id',
 'sequence_index': None,
 'entity_columns': [],
 'context_columns': []}

In [59]:
B1_1

2